### ISSUE TITLE
[SOLVED] Alternatives to jsonstore.io - cook the books example chapter 07

### ISSUE THREAD

**Issue by kalwalt** [PacktPublishing/Learn-WebAssembly#10]
Since jsonstore.io is down i was wondering if there are some alternative to it. I found [jsonbin.io](https://jsonbin.io/) but not sure that can work as jsonstore.io. @mikerourke have you an idea if can be a good replacement? Thank you

**EDIT:** for an updated version of this example clone this repo https://github.com/mikerourke/learn-webassembly

the cook the books example here: https://github.com/mikerourke/learn-webassembly/tree/master/chapter-07-cook-the-books

**Comment by mikerourke** [comment]
Hi @kalwalt, there is a good replacement! So within the `/chapter-07-cook-the-books` directory, run this command:
```
npm install json-server concurrently
```

Then update the `scripts` block in `package.json` to be the following:
```json
"scripts": {
  "start:api": "json-server --watch \"config/db.json\" --port 4001",
  "start:web": "browser-sync start --server \"src\" --files \"src/**\" --single --no-open --port 4000",
  "start": "concurrently --kill-others \"npm run start:api\" \"npm run start:web\""
},
```

Finally, change the `API_URL` in `/src/store/api.js` to the following:
```js
const API_URL = 'http://localhost:4001';
```

Once that's done, run `npm start` and navigate to `localhost:4000` in your browser and you're good to go!. Let me know if you run into any issues.

**Comment by mikerourke** [comment]
@kalwalt Hold that thought! I realized the `db.json` file is actually named `data.json` and you have to make a _slight_ adjustment to that `/config/data.json` file. If you open up that `data.json` file now, you'll see this:
```json5
[
  {
    "id": 1000,
    "transactionDate": "2017-08-02",
    "toFrom": "Uncle Buck's Insurance",
    "type": "Withdrawal",
    "category": "Insurance",
    "rawAmount": -1200,
    "cookedAmount": -1000,
    "description": "Insurance for business"
  },
  // ... all the other records ...
]
```
You need to put that array of objects into an object named `transactions`, so it should look like this:
```json5
{
  "transactions": [
    {
      "id": 1000,
      "transactionDate": "2017-08-02",
      "toFrom": "Uncle Buck's Insurance",
      "type": "Withdrawal",
      "category": "Insurance",
      "rawAmount": -1200,
      "cookedAmount": -1000,
      "description": "Insurance for business"
    },
    // ... all the other records ...
  ]
}

**Comment by kalwalt** [comment]
Thanks @mikerourke i will try It! 🙂

**Comment by kalwalt** [comment]
Dear @mikerourke i tested your suggested changes but accessing the web page at `localhost:4000` i get this error: 

```
main.js:25 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at api.js:44
    at async initializeStore (store.js:133)
```

It seems something related to fetching the wasm resources? I'm investigating...

**Comment by mikerourke** [comment]
@kalwalt I think the easiest way to get around this is to clone the repo I maintain separately from the Packt version. I think this code is pretty much frozen. I can talk to Packt about putting in a PR, but in the interim, I updated my version to work with `json-server`. Could you try cloning **https://github.com/mikerourke/learn-webassembly**?

It has updated data and the required dependencies already: https://github.com/mikerourke/learn-webassembly/tree/master/chapter-07-cook-the-books

**Comment by kalwalt** [comment]
@mikerourke this definetely solved the issue, the example works perfectly! It would a great idea to update this repository with a PR. Many thanks for your support,
Walter

P.s. I will test the other examples. Note that `The cook the books` example works fine with 2.0.8 emsdk version.

**Comment by mikerourke** [comment]
That's great to hear! I'll ask Packt about the PR. Let me know if you have any other issues. I hope you're enjoying the book!

**Comment by kalwalt** [comment]
Yes i'm enyoing the book, there aren't so many books on the WebAssembly topic!

**Comment by kalwalt** [comment]
I will update the first comment with a link to your repo, if in case other people encounter this issue.
