### ISSUE TITLE
Chapter 7 _addTransaction is not a function

### ISSUE THREAD

**Issue by bastet77** [PacktPublishing/Learn-WebAssembly#3]
Using the sample code I get 

main.js:25 TypeError: this.instance._addTransaction is not a function
    at WasmTransactions.addToWasm (WasmTransactions.js:40)
    at WasmTransactions.js:60
    at Array.forEach (<anonymous>)
    at WasmTransactions.populateInWasm (WasmTransactions.js:60)
    at Object.populateTransactions (store.js:41)
    at initializeStore (store.js:134)

Windows 10 plus Chrome.

**Comment by mikerourke** [comment]
@bastet77 I suspect this issue is related to breaking changes in the EMDSK, but you should be able to get it up and running if you follow my instructions in issue #2.

I just tried it on a clean MacBook Air with no prior EMSDK installation/configuration and it worked.

**Comment by bastet77** [comment]
Hi Mike,

 

Many thanks for the response. With a little perseverance I got chapter 5 working by adding the following  

 

"-s", "EXPORTED_FUNCTIONS=['_init,_getIsRunning,_setIsRunning,_moveRect']", 

 

to my tasks.json.  

 

I will try your solution. Onwards and upwards……

 

Regards,

 

Ed Holt

**Comment by bastet77** [comment]
Hi,

 

I followed your instructions but on the compile I got :-

 

You are now entering Powershell : Ed

emcc:WARNING: WASM_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see http://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#codegen-effects

shared:ERROR: Your fastcomp compiler is out of date, please update! (need >= 1.38.26)

The terminal process terminated with exit code: 1

 

Press any key to close the terminal.

 

Even though the WASM is built ( I deleted the previous one) if I tried to load it into the browser (cache refreshed)I get :-

 

without-glue:1 Uncaught (in promise) CompileError: WebAssembly.compile(): expected magic word 00 61 73 6d, 

found 42 43 c0 de @+0

:8080/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)

 

No, problem though, I use the latest version with the addition EXPORT_FUNCTIONS statement.

 

Have a good weekend.

 

Regards,

 

Ed Holt

**Comment by bastet77** [comment]
Hi Mike,

 

As an update I have now got to Chapter 7 without any issues providing I use the EXPORTED_MODULES parameter. In Chapter 8, when trying to build the native Tetris I get the following:-

 

C:\webassembly\book-examples\chapter-08-tetris\output-native> cmake ./ -Bbuild

-- Building for: Visual Studio 14 2015

-- Selecting Windows SDK version 10.0.10586.0 to target Windows 10.0.17763.

-- The C compiler identification is MSVC 19.0.24210.0

-- The CXX compiler identification is MSVC 19.0.24210.0

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

CMake Error at CMakeLists.txt:8 (message):

  You cannot build on your platform.

 

Regards,

 

Ed Holt

**Comment by bastet77** [comment]
Hi,

 

In Chapter 8, the “Make” works fine and Tetris is up and running…..

 

Regards,

 

Ed Holt

**Comment by mikerourke** [comment]
@bastet77 Good news! I apologize for all of the issues. The EMSDK/Emscripten breaking changes really caused a ruckus. Please let me know if you need anything else.

**Comment by bastet77** [comment]
Hi,

 

No problems Mike…..I learnt bucket loads which is always a positive. Thanks for your help and support.

 

Regards,

 

Ed

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if the issue still persists

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if issue persists.
