### ISSUE TITLE
Chapter 9 build fails with "error: undefined symbol: jsClearRect"

### ISSUE THREAD

**Issue by zstauber** [PacktPublishing/Learn-WebAssembly#4]
This is on the webpack-example
I also get
> warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
But I am not sure where to add this while using the webpack build.

Node.js version 8.11.1
Emscripten SDK 1.38.15
Webpack 4.16.5
Webpack-CLI 3.1.0
Webpack-dev-server 3.1.5

**Comment by zstauber** [comment]
I couldn't figure out how to set that setting, but in the emsdk file **emcc.py** I found the lines:
```
if 'WARN_ON_UNDEFINED_SYMBOLS=0' in settings_changes:
        shared.Settings.ERROR_ON_UNDEFINED_SYMBOLS = 0
```
and just under them I added the line:
`shared.Settings.ERROR_ON_UNDEFINED_SYMBOLS = 0`
And that actually allowed me to compile and run it with **serve -l 8080 dist**
So I went ahead and undid that in emcc.py once I had built it, but it does show that build flag will work.  I just don't know how to make it standard instead of a workaround.

**Comment by mikerourke** [comment]
@zstauber I apologize for the _extremely_ long delay with this response. I wasn't getting notified of issues on this repo. I figured out how to fix the issue, if you're still interested.  You can update the `webpack.config.js` file with the following for the `c|cpp` rule: 

```js
{
  test: /\.(c|cpp)$/,
  use: {
    loader: 'cpp-wasm-loader',
    options: {
      emitWasm: true,
      // This will prevent the error going forward:
      emccFlags: (existingFlags) => [
        ...existingFlags,
        '-s',
        'ERROR_ON_UNDEFINED_SYMBOLS=0'
      ]
    }
  }
},
```

**Comment by zstauber** [comment]
I very much appreciate it, Mr. Rourke, and I totally understand about not getting the notifications as expected.  I will try this out soon.
